services:
  mysql:
    container_name: 'home-improvement-mysql'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=home-improvement-database'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=xJwOnkcMBY7DGAw'
      - 'MYSQL_USER=bswiech'
    ports:
      - '3306:3306'